### ISSUE TITLE
The method and call to the Tweakwise helper Slugify gives an error:

### ISSUE THREAD

**Issue by igorwulff** [EmicoEcommerce/Magento1TweakwiseExport#8]
class Emico_TweakwiseExport_Model_Observer_UrlMapping
/**
     * @return Emico_Tweakwise_Helper_Slugifier
     */
    protected function getSlugifier()
    {
        return Mage::helper('emico_tweakwise/slugifier');
    }

PHP error: "Uncaught Error: Class 'Emico_Tweakwise_Helper_Slugifier' not found in"

I couldn't find this helper in a recent Emico Tweakwise stable version and if there is a dependency that we should know of, then restrictions should be set in the composer.json.

_Originally posted by @igorwulff in https://github.com/EmicoEcommerce/Magento1TweakwiseExport/commit_comment/create#commitcomment-31202994_

**Comment by edwinljacobs** [comment]
Hi

Unfortunately the code that produces this error should not be there. It is supposed to be part of a feature which is yet to come. We have released a new tag in which the observers that require the slugifier helper are deleted from config.xml so that the error will not occur. In the future there will be a release where this is enabled again.

the new tag is 2.2.3,

With kind regards

**Comment by edwinljacobs** [comment]
Ill close this issue for now
